### ISSUE TITLE
launch_user.bat didn't accept commandline_args on windows

### ISSUE THREAD

**Issue by ruSauron** [toshiaki1729/dataset-tag-editor-standalone#1]
To fix modify last line from
`call ".\scripts\launch.bat %COMMANDLINE_ARGS%"`
to
`call ".\scripts\launch.bat" %COMMANDLINE_ARGS%`

I tried to make it into a commit
3f0bf56345589889a1c1b973715eabdccd873700

**Comment by ruSauron** [comment]
Another small issue.
install.bat didnt installed torch but it can be my issue so i've used following command after venv\scripts\activate.bat:
`pip3 install torch==1.13.1+cu117 torchvision>=0.13.1+cu117 torchaudio>=0.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117 --no-cache-dir `

**Comment by toshiaki1729** [comment]
Added the description about PyTorch version and in the Requirements section.
PyTorch>=1.10.0 is from requirements of [onnx-pytorch](https://github.com/fumihwh/onnx-pytorch) ([TorchDeepDanbooru](https://github.com/AUTOMATIC1111/TorchDeepDanbooru) is generated with it).

**Comment by toshiaki1729** [comment]
Plus, added command line option to force install pytorch, `--force-install-pytorch {cu117, cu118, cpu}`.
