### ISSUE TITLE
[BUG] After reloding, `on_filter_update_callbacks` was not cleared

### ISSUE THREAD

**Issue by WSH032** [toshiaki1729/dataset-tag-editor-standalone#16]
@toshiaki1729 

https://github.com/toshiaki1729/dataset-tag-editor-standalone/blob/3ddf4c4a92a28fec9a5388792d73ba85db3cc437/scripts/interface.py#L160

If you set
```diff
- analytics_enabled=False
+ analytics_enabled=True
```
And reload UI, you will notice that.

---

This is because the following two lists were not cleared after restarting
```python
ui.filter_by_tags.tag_filter_ui.on_filter_update_callbacks
ui.filter_by_tags.tag_filter_ui_neg.on_filter_update_callbacks
```

So it will add callback function for the previous Gradio.Blocks components.
That will be found by  Gradio analytics, and raise error.
```python
self.tag_filter_ui.set_callbacks()
self.tag_filter_ui_neg.set_callbacks()
```

**Comment by toshiaki1729** [comment]
I think this script doesn't have reloading feature.
How you could?

**Comment by WSH032** [comment]
Set `analytics_enabled=True`
![@@R@HRS9KZ{_}DBB(24_N0G](https://github.com/toshiaki1729/dataset-tag-editor-standalone/assets/126865849/b4b22fd6-9569-4fb1-8802-a03419e15eae)

Then `Reload UI`
![7CVKR~XA@)$ 0S9BZLCB)KO](https://github.com/toshiaki1729/dataset-tag-editor-standalone/assets/126865849/cb873a3f-9624-4ca3-8941-0d6726a499f7)

You will notice that
![1$FTQTI6BXU2ARU94SPNI_P](https://github.com/toshiaki1729/dataset-tag-editor-standalone/assets/126865849/10f505a7-509d-4a70-b34a-e08b0f481db3)

**Comment by WSH032** [comment]
I use your repository while creating [WSH032/sd-webui-fast-dataset-maker](https://github.com/WSH032/sd-webui-fast-dataset-maker), and at that time I discovered this issue

I fix it by this way
https://github.com/WSH032/dataset-tag-editor-standalone/blob/ec8617609c38888b24b04593751e2c2e056242d3/scripts/tab_main.py#L517C1-L520C76

And, your repository is really awesome.

**Comment by toshiaki1729** [comment]
>I think this script doesn't have reloading feature.

https://github.com/toshiaki1729/dataset-tag-editor-standalone/blob/6d827f1a9827821604f473429ffdb80851d2722e/scripts/tab_settings.py#L49

Confirmed: I don't know anything about my script

Anyway, thank you so much for utilizing this repository.

>By the way, Gradio has already fixed it https://github.com/gradio-app/gradio/issues/4642

I understand that it will be fixed, but I will look into it in more detail just to be sure.

**Comment by WSH032** [comment]
Great!

---

I still hava another issue, have you noticed that if don't turn on thumbnails, loading will become incredibly slow

And once multiple images are loaded, the tag filter will no longer work

Should I open another issue?

**Comment by toshiaki1729** [comment]
I've updated gradio to 4.28.3 in >= ver0.0.6.
And the issue when loading many images may be solved.
I'm grad if you can check it.
