### ISSUE TITLE
After repeated attempts, I found that，When I put this version into extensions File folder,webui Failed to start。

### ISSUE THREAD

**Issue by openwaterer** [toshiaki1729/dataset-tag-editor-standalone#17]
Because of dataset-tag-editor In web ui the front end is stuck,unable to work properly，I found this version，after installation ,This is through the cloud server.JupyterLab start up.The following is the relevant result code output after startup：
启动带有参数的Web UI：-f --port 6006 --enable-insecure-extension-access --api --xformers --opt-sdp-attention --no-half-vae --ckpt-dir /root/autodl-tmp/models/ckpt --embeddings-dir /root/autodl-tmp/models/embeddings --lora-dir /root/autodl-tmp/models/lora --vae-dir /root/autodl-tmp/models/vae --controlnet-dir /root/autodl-tmp/models/controlnet --skip-torch-cuda-test --skip-version-check --skip-python-version-check
launch.py：错误：未识别的参数：-f --enable-insecure-extension-access --api --xformers --opt-sdp-attention --no-half-vae --ckpt-dir /root/autodl-tmp/models/ckpt --embeddings-dir /root/autodl-tmp/models/embeddings --lora-dir /root/autodl-tmp/models/lora --vae-dir /root/autodl-tmp/models/vae --controlnet-dir /root/autodl-tmp/models/controlnet --skip-torch-cuda-test --skip-version-check --skip-python-check

**Comment by openwaterer** [comment]
This question is so strange，Why does the extension affect startup?

**Comment by openwaterer** [comment]
This question is too strange. Why does the extension affect startup?

**Comment by toshiaki1729** [comment]
@openwaterer 
This script is standalone, it means this is not the extension of Automatic1111's SD webUI.
Since the folder structure is similar to the extension version, putting this into `extensions` folder of webUI may lead to unexpected result.

**Comment by openwaterer** [comment]
hh Thanks  I want to delete this question
