### ISSUE TITLE
[solved] pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody

### ISSUE THREAD

**Issue by deefster** [toshiaki1729/dataset-tag-editor-standalone#30]
requirements.txt should be updated to reflect gradio=3.50.2

When interacting with gradio on a new install, pydantic error
I found similar issue reported on the gradio github 
https://github.com/gradio-app/gradio/issues/6914
I followed recommendation of upgrading to gradio==3.50.2 (works)
Note - 4.x wont work, so dont go to the latest.

**Comment by superpeachman** [comment]
Great! Thanks. @deefster

**Comment by toshiaki1729** [comment]
I've updated gradio to 4.28.3 in >= ver0.0.6.
Version related issue may be solved. I'm grad if you can check it.
