### ISSUE TITLE
Image selection not working

### ISSUE THREAD

**Issue by ccharest93** [toshiaki1729/dataset-tag-editor-standalone#31]
While using gradio==3.50.2 as per #30. I was getting a bug where image selection wasn't properly working. Whenever i would click on an image `Selected Image : ` would stay empty. I fixed it by modifying 

https://github.com/toshiaki1729/dataset-tag-editor-standalone/blob/f13a919fabb71516c679493a488913f6d0723ea4/javascript/10_modified_gallery.js#L12

to

`this.#items_selector = this.#elem.querySelectorAll('button.preview > div.thumbnails > button.thumbnail-item')`

**Comment by toshiaki1729** [comment]
I've updated gradio to 4.28.3 in >= ver0.0.6.
Selection behavior is completely changed and the issue may be solved.
I'm grad if you can check it.
