### ISSUE TITLE
Images do not load

### ISSUE THREAD

**Issue by without-ordinary** [toshiaki1729/dataset-tag-editor-standalone#36]
**Describe the bug**
No images from dataset are able to load since the gradio update. All images are 403.

**To Reproduce**
1. Install and run per normal
2. Load any dataset that previously worked
3. No images load, browser console has 403 errors for each dataset image, no output in terminal.

**Expected behavior**

**Screenshots**
![image](https://github.com/toshiaki1729/dataset-tag-editor-standalone/assets/20104884/15e78a2e-bc6e-4374-babe-7b2a1928a980)

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 20.04
 - Browser: Firefox 125.0.2 and Chrome 124.0.6367.118
 - Version of this app: [6192be5](https://github.com/toshiaki1729/dataset-tag-editor-standalone/commit/6192be546fb9d9f16ca5a038739bbe1d9e97fddd) on Python 3.10.14

**Additional context**
Initially did an upgrade and got this issues. Did a complete fresh install for testing and repo'd the issue there too.

**Comment by toshiaki1729** [comment]
[Possible solutions are here](https://github.com/toshiaki1729/dataset-tag-editor-standalone?tab=readme-ov-file#trouble-shooting)

**Comment by without-ordinary** [comment]
That was exactly it, thanks.

Had checked settings, didn't see anything obvious, but light gray text Gradio uses is quite hard for me to read (that's accessibility issue with Gradio itself, and general all Modern UI design that loves gray on grey for their neglected light themes), so I missed that. Derp.
