### ISSUE TITLE
Preview images wont show up. 

### ISSUE THREAD

**Issue by DarqueLilly** [toshiaki1729/dataset-tag-editor-standalone#49]
![chrome_B71X72a6rJ](https://github.com/toshiaki1729/dataset-tag-editor-standalone/assets/111714884/1f331f68-bd00-467a-a143-ccdffae0428a)

When I load the folder, I get blank picture squares. The tags come through but the picture previews doesn't show.

**Comment by netadnis** [comment]
I also encountered the same symptoms, but I discovered that the 'Settings > Maximum resolution of gallery thumbnails' value was set to 0. After correcting this, the thumbnails displayed correctly.

**Comment by toshiaki1729** [comment]
Please see [the troubleshooting](https://github.com/toshiaki1729/dataset-tag-editor-standalone?tab=readme-ov-file#cannot-see-any-image-in-dataset-and-no-error-is-shown)
Gradio limits directory of images to display and you have to whitelist them or use temporal thumbnails.
