### ISSUE TITLE
Feature Request:  Allow us to choose where to download models

### ISSUE THREAD

**Issue by Vigilence** [toshiaki1729/dataset-tag-editor-standalone#5]
I just noticed that the models cache default to the C: drive and I would appreciate it if I can download it in a folder of my choosing, preferably the folder that includes the stand alone tag editor.

![2023-05-02_01-55-49](https://user-images.githubusercontent.com/22781570/235589957-65657933-2646-48dd-a6f2-1b9dc02d3241.jpg)

**Comment by toshiaki1729** [comment]
Added option in the Setting tab
