### ISSUE TITLE
batch file not recognized as internal or external comm and, operable program or batch file

### ISSUE THREAD

**Issue by vordac1** [toshiaki1729/dataset-tag-editor-standalone#55]
**Describe the bug**
the startup batch file does not work

**To Reproduce**
run the batch file

**Expected behavior**
Program starts

**Screenshots**
Screen shot of error attached

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version of this app: v0.2.4
![C__Windows_system32_cmd exe 8_6_2024 2_58_58 PM](https://github.com/user-attachments/assets/84f74f2e-d046-443c-929e-458e8a3671ac)

**Additional context**

**Comment by toshiaki1729** [comment]
duplicate issue #53
