### ISSUE TITLE
CUDA device is not used

### ISSUE THREAD

**Issue by dramumard** [toshiaki1729/dataset-tag-editor-standalone#9]
I have a working NVIDIA GPU of Ampere generation. AUTOMATIC1111 and other projects have no problem using the CUDA device, but not dataset-tag-editor-standalone (for automatic captioning).

Windows 11
NVIDIA RTX A4500
NVIDIA Driver 528.95
tag editor on latest commit (024966c1addeb847729db53da1510cf98dc9ae2b)

**Comment by dramumard** [comment]
Issue solved, dataset-tag-editor-standalone is installing a too old version of CUDA.

My guess was that your install.bat script is not installing pytorch with CUDA support. I went to the pytorch site and looked up the recommended install command. Ofc I activated the virtual environment first.

On [this page](https://pytorch.org/get-started/pytorch-2.0/) it says: 
> pip3 install numpy --pre torch --force-reinstall --index-url https://download.pytorch.org/whl/nightly/cu117

Note this installs a version for CUDA 11.7.

But still  the only the CPU was used.

Later down on the same page though, in the FAQ, there is also a different install command that uses CUDA 11.8:
>  pip3 install numpy --pre torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/nightly/cu118

And now it works, CUDA is detected and used.

I recommend adjusting the standalone dataset-tag-editor's install scripts to use CUDA 11.8.

**Comment by toshiaki1729** [comment]
As mentioned in [Requirements](https://github.com/toshiaki1729/dataset-tag-editor-standalone#requirements) section, this scripts require pre-installed CUDA.
Or, if you want to re-install into venv, you can use `--force-install-torch` command line argument.

**Comment by pylorak** [comment]
You're right, I'm sorry. Apparently I subconsciously skipped the requirements: saw "Installation", for Windows "Just run install.bat", and I was done reading :)

**Comment by jibbersmcgee** [comment]
I've got the same issue however i have cuda 12.1, pytorch 2.0. any ideas?

**Comment by toshiaki1729** [comment]
> I've got the same issue however i have cuda 12.1, pytorch 2.0. any ideas? 

Here you can see whether the PyTorch is installed with CUDA properly or not.
![ss](https://github.com/toshiaki1729/dataset-tag-editor-standalone/assets/116595002/67b713a5-f7c8-4a02-86a1-b0e33477bf8d)

If your PyTorch version is without `+cu117` or `+cu118`, you may need to re-install PyTorch.
- If You want to install PyTorch in your system and use it (to share PyTorch with other scripts)
  1. Follow [the PyTorch installation guide](https://pytorch.org/get-started/locally/) with -U (--upgrade) option
  (example) ```pip3 install -U torch torchvision --index-url https://download.pytorch.org/whl/cu118```
  1. Remove `venv` folder
  1. Run `install.bat`
- If you want to install PyTorch only in venv
  1. Open `launch_user.bat` to edit
  2. `set COMMANDLINE_ARGS="--force-install-torch cu118"` (you can choose from `cu117`, `cu118` or `cpu`)

**Comment by jibbersmcgee** [comment]
Thank you. The launch CMD window says my device is CPU but it is actually
using the video card.

**Comment by jibbersmcgee** [comment]
Yes I'm using WD. Maybe I'm misunderstanding. The device is listed as cpu
but when i run the tagger, my GPU usage is 100% and it's very quick. It's
working just fine but maybe there's something i don't understand.
